### ISSUE TITLE
Missing sound files

### ISSUE THREAD

**Issue by bob0bob** [Glitchfiend/FamiliarFauna#1]
I compiled your code and ran it and it is missing files.   

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.12-3.0.0.62-universal.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 9/3/17 10:45 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Familiar Fauna (familiarfauna)
Caused by: java.lang.NoSuchFieldError: ENTITY_SHEEP_STEP
	at familiarfauna.init.ModSounds.init(ModSounds.java:19)
	at familiarfauna.core.FamiliarFauna.preInit(FamiliarFauna.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:628)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

**Comment by bob0bob** [comment]
I'm sorry it is something I'm doing.  I can run things I compile in programming environment but can't run against live stuff.   I figure it is a mapping thing.  The variable is define, but the forge I use for playing and programming must be different even though I"ve verify the version numbers are the same.
